import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import Sidebar from "./components/sidebar/sidebar";
import { ExpenseProvider } from "./context/ExpenseContext"; // import the provider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Expense tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        {/* ExpenseProvider wraps everything so both the Sidebar
            and all pages can access the expenses list */}
        <ExpenseProvider>
          <Sidebar />
          {children}
        </ExpenseProvider>
      </body>
    </html>
  );
}